version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: job_recommendation_db
    environment:
      POSTGRES_DB: job_recommendation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: job_recommendation_app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=job_recommendation
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/__pycache__
    command: python src/main.py

volumes:
  postgres_data:
